COUNTRY_ALIASES: dict[str, str] = {
    "United Kingdom of Great Britain and Northern Ireland":         "UK",
    "Iran (Islamic Republic of)":                                   "Iran",
    "China, People's Republic of":                                  "China",
    "Korea, Republic of":                                           "South Korea",
    "Korea, Dem. People's Rep. of":                                 "North Korea",
    "Russian Federation":                                           "Russia",
    "Syrian Arab Republic":                                         "Syria",
    "Lao People's Democratic Republic":                             "Laos",
    "Tanzania, United Republic of":                                 "Tanzania",
    "Congo, Dem. Rep. of the":                                      "DR Congo",
    "Congo, Republic of the":                                       "Congo",
    "Democratic Republic of the Congo":                             "Democratic Congo",
    "Central African Republic":                                     "CAR",
    "Trinidad and Tobago":                                          "Trinidad & Tobago",
    "Antigua and Barbuda":                                          "Antigua & Barbuda",
    "Saint Kitts and Nevis":                                        "St Kitts & Nevis",
    "Saint Vincent and the Grenadines":                             "St Vincent",
    "Bosnia and Herzegovina":                                       "Bosnia & Herz.",
    "The former Yugoslav Republic of Macedonia":                    "N. Macedonia",
    "United States of America":                                     "USA",
    "Venezuela, Bolivarian Republic of":                            "Venezuela",
    "Bolivia (Plurinational State of)":                             "Bolivia",
    "Micronesia (Federated States of)":                             "Micronesia",
    "Papua New Guinea":                                             "Papua NG",
    "Equatorial Guinea":                                            "Eq. Guinea",
    "São Tomé and Príncipe":                                        "São Tomé",
    "Brunei Darussalam":                                            "Brunei",
    "Viet Nam":                                                     "Vietnam",
    "United Arab Emirates":                                         "UAE",
    "United Republic of Tanzania":                                  "Tanzania",
    "Venezuela (Bolivarian Republic of)":                           "Venezuela",
    "China, Hong Kong Special Administrative Region":               "Hong Kong",
    "China, Macao Special Administrative Region":                   "Macao",
    "Democratic People's Republic of Korea":                        "North Korea",
    "Sao Tome and Principe":                                        "São Tomé",
    "Côte d'Ivoire":                                                "Ivory Coast",
}